<template>
  <div id="app">
    <router-view></router-view>
  </div>

  
</template>

<script>
export default {
  name: 'app'
}
</script>

<style>

body
{
  width: 700px;
  margin: 0px auto;
  background: linear-gradient(#deedfc, #becbd8);
}

#app {
  /*CSS generated by Vue*/
  font-family: 'Avenir', Helvetica, Arial, sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  color: #2c3e50;
  margin-top: 30px;
  background: white;
  
  /* My CSS */
  display: flex;
  justify-content: center;
  min-height: 100vh;
  padding: 30px;
  box-shadow: 0px 3px 7px 0px #c3c3c3;
  border-radius: 1px;
}
</style>